### PR TITLE
Improve linting and run on all files

### PR DESCRIPTION
**Pull request by paddyroddy**

### CODE REVIEW

**Review by p-j-smith — CHANGES_REQUESTED** [review]
I think you'll need to add:

```py
from __future__ import annotations
```
to each module with type hints

**Comment by p-j-smith** [comment]
There's an [error about magicgui](https://github.com/epitools/napari-epitools/actions/runs/4315667572/jobs/7530423565#step:7:45) now, but the linting is passing! Shall we fix the tests in a separate pr?

**Comment by paddyroddy** [comment]
Getting some very weird errors. Help welcomed!

**Comment by p-j-smith** [comment]
the tests are passing locally now including with tox. And they even pass in ci, but then [the runner crashes after the tests have finished](https://github.com/epitools/napari-epitools/actions/runs/4323174155/jobs/7546463783#step:7:147)

**Comment by paddyroddy** [comment]
I was getting similar too. I think it's something to do with `pytest-xvfb`.

**Review by p-j-smith — APPROVED** [review]

**Comment by paddyroddy** [comment]
> seeing as the tests and linting is passing locally shall we merge this and fix the ci issues in another pr?

Yeah makes sense

**Comment by paddyroddy** [comment]
> seeing as the tests and linting is passing locally shall we merge this and fix the ci issues in another pr?

Can you raise the issue please?

**Pull request merged**
